### ISSUE TITLE
Tell the user why they missed the collection?

### ISSUE THREAD

**Issue by glowkeeper** [minima-global/incentivecash#2]
If a user misses a collection (perhaps they didn't have the apk running, or the apk has disconnected from the network), would it be possible to tell them _why_ they missed the collection?

**Comment by eliasnemr** [comment]
Not sure how we can automate this step.. naturally the only reason they miss it is if their node isn't connected to the network, then it'll check the script & if window is > Minima.block it'll just say Missed.. any ideas?

**Comment by eliasnemr** [comment]
Only reason would be node is off?

**Comment by glowkeeper** [comment]
Or apk not connected (because it went into sleep mode) - which is what happened to someone last night...

**Comment by glowkeeper** [comment]
A quick fix might be to have a modal or tooltip that says "Either Minima was not running or it was disconnected from the network" - something like that, maybe?

**Comment by eliasnemr** [comment]
If you tap Missed Collection there's an alert that says the reasons
