### ISSUE TITLE
Keep the date of missed collections

### ISSUE THREAD

**Issue by glowkeeper** [minima-global/incentivecash#3]
When a collection is missed it replaces the date of the missed transaction with 'Missed' - since 'Collection missed' is already listed on the right-hand side, it would be good to keep the date of the transaction so that we can handle any potential disputes properly (i.e. we would know the exact date and time of the scheduled collection)

**Comment by eliasnemr** [comment]
With this bug we previously agreed that I'd just attach Missed for due date so I don't calculate the date backwards, where:

`.    let currenttime = new Date().getTime();
        let blockdifference = unlockblock - currentblock;
        let timedifference_ms = blockdifference*20*1000;
        currenttime = currenttime + timedifference_ms;
        let time = moment(currenttime).format('DD-MM-YYYY HH:mm');
        cash.time = time;
`

I could do if ( unlockblock < currentblock) { // calculate backwards }..

**Comment by glowkeeper** [comment]
The Community Engagement team have asked us to keep the date in case they need to resolve a conflict. And they point out that there's already _Collection Missed_ in the 3rd column...

**Comment by glowkeeper** [comment]
Fixed
